package:
  name: pyisc
  version: "develop"

source:
  path: .

requirements:
  build:
    - swig
    - python
    - numpy
    - requests
    - setuptools
    - mingw [win]
    - libpython 1.0 [win]
    - posix  #unfortunetly needed
    - m2-git
  run:
    - libcxx [not win]
    - python
    - numpy
    - scipy
    - scikit-learn

test:
  imports:
    - pyisc

about:
  home: https//www.sics.se
  license: LGPLv3
  license_file: LICENSE
