package:
  name: pyisc
  version: "master"

source:
  path: .

requirements:
  build:
    - swig
    - python
    - numpy
    - requests
    - setuptools
  run:
    - libcxx [not win]
    - python
    - numpy
    - scipy
    - scikit-learn

test:
  imports:
    - pyisc

about:
  home: https//www.sics.se
  license: LGPLv3
  license_file: LICENSE
