package:
  name: pyisc
  version: "develop"

source:
  path: .

build:
  detect_binary_files_with_prefix: True


requirements:
  build:
    - swig
    - python {{python}}
    - numpy
    - requests
    - setuptools
    - mingw [win]
    - libpython 1.0 [win]
    - mkl 2017.0.3 [win]

  run:
    - libcxx [not win]
    - python
    - numpy
    - scipy
    - scikit-learn
    - swig
    - libpython 1.0 [win]
    - mkl 2017.0.3 [win]


test:
  imports:
    - pyisc

about:
  home: https//www.sics.se
  license: LGPLv3
  license_file: LICENSE
