package:
  name: pyisc
  version: "beta2"

source:
  git_rev: beta2
  git_url: https://github.com/STREAM3/pyISC.git

requirements:
  build:
    - python
    - numpy
    - requests
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - scikit-learn

test:
  imports:
    - pyisc

about:
  home: https//www.sics.se
  license: LGPLv3
  license_file: LICENSE.md
